FROM node:alpine
MAINTAINER Nathan LeClaire <nathan@docker.com>

ADD . /app
WORKDIR /app/wetty

RUN apk --no-cache add g++ gcc libgcc libstdc++ linux-headers make python bash
RUN npm --quiet install

RUN echo 'alias 5gmediavalidate="node /app/SDK-Validator/bin/5gmediavalidate.js"' >> ~/.bashrc
RUN echo 'cd /app/SDK-Validator/test/'  >> ~/.bashrc
RUN tail -2 ~/.bashrc

EXPOSE 3000

ENTRYPOINT source ~/.bashrc
ENTRYPOINT ["node"]
CMD ["/app/wetty/app.js", "-p", "3000"]
